name: Build APK

on:
  push:
    branches:
      - main  # Replace with the desired branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.3'  # Replace with the desired Flutter version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: flutter pub get

    - name: Clean project
      run: flutter clean

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: build/app/outputs/flutter-apk/app-release.apk
